version: 2.1

jobs:
  build:
    machine:
      image: 'windows-server-2019-vs2019:2022.08.1'
    steps:
      - checkout
      - run:
          name: "build"
          command: .\build.ps1
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

workflows:
  build-workflow:
    jobs:
      - build
