version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    machine:
      image: windows-server-2019
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "build"
          command: .\build.ps1
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

workflows:
  build-workflow:
    jobs:
      - build
